title: Shashank S Basty
logo: /assets/img/IMG_1134.jpeg
description: ğŸ“Boston, USA | ğŸ“§ ssbasty@bu.edu | ğŸ“± +1 (857) 245-8992 | X - shanksbasty |


show_downloads: false
theme: jekyll-theme-minimal
